# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'resq_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for resq_ios
  pod 'TwilioVoice', '~> 6.5.0'
  
  target 'resq_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'resq_iosUITests' do
    # Pods for testing
  end

end
